defaults: &defaults
  host: localhost
#   slaves:
#     - host: slave1.local
#       port: 27018
#     - host: slave2.local
#       port: 27019
  allow_dynamic_fields: false  # true
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: true
  autocreate_indexes: false

development:
  <<: *defaults
  database: lojban-dev

test:
  <<: *defaults
  database: lojban-test

production:
  <<: *defaults
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  pool_size: 10
