defaults: &defaults
#   slaves:
#     - host: slave1.local
#       port: 27018
#     - host: slave2.local
#       port: 27019
  allow_dynamic_fields: false  # true
  parameterize_keys: true
  persist_in_safe_mode: false
  raise_not_found_error: true
  reconnect_time: 3
  use_object_ids: true
  autocreate_indexes: false

development:
  <<: *defaults
  host: localhost
  database: lojban-dev

test:
  <<: *defaults
  host: localhost
  database: lojban-test

production:
  <<: *defaults
  uri: <%= ENV['MONGODB_URL'] %>
  pool_size: 10
